name: Publish to Conda

on:
  # Triggers the workflow on a new release
  # release:
  #   types: [created]
  push:
    branches:
      - conda-build
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: publish-to-conda
      uses: fcakyon/conda-package-publish-action@v1.1
      with:
        subdir: 'conda'
        anacondatoken: ${{ secrets.ANACONDA_TOKEN }}