name: Publish to Conda

on:
  # Triggers the workflow on a new release
  # release:
  #   types: [created]
  push:
    branches:
      - conda-build
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: publish-to-conda
      uses: jegp/conda-package-publish-action@v1.5
      with:
        subDir: 'conda'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}